⚡️ Improve search
laminlabs/lamindb pull request #2135
Opened 2024-11-06 11:22 UTC by sunnyosun

2024-11-07 13:14 UTC, Koncopd commented
@sunnyosun @falexwolf here is the benchmark for this PR https://github.com/laminlabs/lamindb/pull/2141

2024-11-07 13:19 UTC, Koncopd approved these changes

2024-11-07 14:27 UTC, falexwolf commented
These are great improvements!

I wish there was good way in laminhub to document such changes but I guess there isn't for now.

2024-11-07 14:28 UTC, falexwolf commented
@fredericenard, please also take a look here.

And then we'll discuss in the benchmarking PR how we proceed with organizing code across lamindb, bionty and laminhub.

2024-11-07 14:28 UTC, falexwolf approved these changes

2024-11-07 14:29 UTC, falexwolf requested changes
One thing that's totally not covered is longer search phrases along the lines of "CD8-positie cytokine T cell"

So, I believe we need a benchmarking case for this.

2024-11-07 17:01 UTC, Koncopd commented
Added more searches to the benchmark. 
`test_search_synonyms`, commented out in the benchmark.

2024-11-07 20:46 UTC, sunnyosun commented
Fixed synonyms. The only thing is that it's getting a bit slower now ~0.8s per search (before 0.2-0.3s) because of all the different layers.

2024-11-08 21:29 UTC, Zethson reviewed
This is really cool!

I know that no review of me was requested but I thought I'd leave a couple of comments still. Feel free to ignore them!

1. Would it be possible to add 1-3 sentences of high level motivation and explanation of this new layered algorithm to the docstring or where appropriate, please?
2. We have the nice search benchmark now. Is there a way to add slightly more sophisticated tests to ensure that no changes of this code will lead to regressions of the search performance? @Koncopd benchmarking notebook is great but it's not regularly run, is it?

These things can also be added later if you think that they're useful...

2024-11-08 21:29 UTC, Zethson commented on lamindb/_record.py
> +        # Split the string
```suggestion
```

2024-11-08 21:29 UTC, Zethson commented on lamindb/_record.py
> +        # Split the string
Self documenting code here.

2024-11-08 22:10 UTC, Zethson commented
Ohh and can we get rid of this now?
![image](https://github.com/user-attachments/assets/d5fcc231-1d45-4e3d-98eb-e0f89b721864)
🚀

2024-11-09 08:23 UTC, falexwolf commented
Yes, removing will be the goal.

<img width="675" alt="image" src="https://github.com/user-attachments/assets/7eb49cc2-f9be-497d-8435-dff3195ff061">

@Koncopd is making a push to consolidate all 3 search algorithms into one clearly documented and benchmarked solution.

Sunny's PR here has good ideas but it's not suitable for the hub due to performance. So, the hope is Sergei can replicate the UX with server-side code (essentially correctly using postgres plugins). We can still use Sunny's code for dataframes and sqlite; it'll give the same results but just run slower which is OK in that context.

2024-11-14 10:13 UTC, closed without merging